/// This file is generated by 'Oh My Script!' extension.
/// It serves as entry of bundle main.
/// Neither don't edit it, nor add it into version control system(eg. Git).

import { loadBundleEntry, saveRequiringFrames } from 'db://oh-my-script/loader';
import { cclegacy} from 'cc';

const restoreRequiringFrames = saveRequiringFrames();
try {
  // @ts-expect-error
  await loadBundleEntry('main', import.meta.url);
} finally {
  restoreRequiringFrames();
}
